# Generated by Django 5.2.11 on 2026-02-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_no', models.IntegerField()),
                ('ayah_no', models.IntegerField()),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moods.mood')),
            ],
        ),
    ]
